# docker-compose.yml  (repo root)
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file: .env
    ports: ["8000:8000"]

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    depends_on: [api]
    ports: ["3000:80"]
