import { useState } from 'react';
import { entrantLabel } from './model.js';
export const percent = n => `${(n * 100).toFixed(1)}%`;
export const wdl = r => `${r.wins}–${r.draws}–${r.losses}`;
export function Standings({ season: s, rows }) {
  return <section className="season-panel season-standings" aria-labelledby="standings-heading"><p className="eyebrow">1 win · ½ draw · 0 loss</p><h2 id="standings-heading">Standings</h2><p className="analysis-helper">Ordered by score points, then score percentage, then entrant seed. Elo ranking is separate.</p><p className="season-scroll-hint">Scroll the table for score and Red / Yellow splits.</p>
    <div className="season-table-scroll" role="region" aria-label="Standings table" tabIndex={0}><table><caption>Overall results and Red / Yellow splits</caption><thead><tr>{['Rank', 'Entrant', 'Played', 'W', 'D', 'L', 'Points', 'Score %', 'Red W-D-L', 'Red score %', 'Yellow W-D-L', 'Yellow score %'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={r.entrantId}><td>{i + 1}</td><th scope="row">{entrantLabel(s, r.entrantId)}</th><td>{r.played}</td><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.points}</td><td>{r.played ? percent(r.scoreRate) : '—'}</td><td>{wdl(r.red)}</td><td>{r.red.played ? percent(r.red.scoreRate) : '—'}</td><td>{wdl(r.yellow)}</td><td>{r.yellow.played ? percent(r.yellow.scoreRate) : '—'}</td></tr>)}</tbody></table></div>
  </section>;
}
export function Ratings({ season: s, ratings, standings, intervals }) {
  return <section className="season-panel season-ratings" aria-labelledby="ratings-heading"><p className="eyebrow">Pool-relative · K = 24</p><h2 id="ratings-heading">Ratings</h2><p className="analysis-helper">Bootstrap intervals summarize uncertainty in observed score rate, not Elo uncertainty. Intervals require at least 8 completed games and use 1000 resamples. Resampling does not account for opponent dependence or unseen outcomes.</p><p className="season-scroll-hint">Scroll the table for Elo, score rate and intervals.</p>
    <div className="season-table-scroll" role="region" aria-label="Ratings table" tabIndex={0}><table><caption>Elo order · deterministic seed order breaks ties</caption><thead><tr>{['Rank', 'Entrant', 'Elo', 'Change', 'Played', 'Score %', 'Observed score-rate bootstrap 95% interval', 'W-D-L'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{ratings.map((r, i) => { const row = standings.find(e => e.entrantId === r.entrantId), interval = intervals[r.entrantId]; return <tr key={r.entrantId}><td>{i + 1}</td><th scope="row">{entrantLabel(s, r.entrantId)}</th><td>{Math.round(r.rating)}</td><td>{r.rating >= 1500 ? '+' : ''}{Math.round(r.rating - 1500)}</td><td>{row.played}</td><td>{row.played ? percent(row.scoreRate) : '—'}</td><td>{interval ? `${percent(interval.lower)}–${percent(interval.upper)}` : 'Too few games for a useful interval.'}</td><td>{wdl(row)}</td></tr>; })}</tbody></table></div>
  </section>;
}
export function Pairwise({ season: s, matrix }) {
  const [selected, setSelected] = useState(s.entrants[0].entrantId);
  const summary = r => `${r.played} games · ${wdl(r)} W-D-L · ${r.played ? percent(r.scoreRate) : 'no score yet'}`;
  return <section className="season-panel season-pairwise" aria-labelledby="pairwise-heading"><p className="eyebrow">Every opponent · both colors</p><h2 id="pairwise-heading">Pairwise results</h2><p className="analysis-helper">Cells show wins–draws–losses and score percentage from the row entrant’s perspective.</p>
    <div className="season-table-scroll pairwise-desktop" role="region" aria-label="Pairwise results matrix" tabIndex={0}><table><caption>Opponent seed numbers match the entrant labels</caption><thead><tr><th scope="col">Entrant</th>{s.entrants.map(e => <th scope="col" key={e.entrantId}>#{e.seedNumber}</th>)}</tr></thead><tbody>{s.entrants.map(e => <tr key={e.entrantId}><th scope="row">{entrantLabel(s, e.entrantId)}</th>{s.entrants.map(o => { const r = matrix[e.entrantId][o.entrantId]; return <td key={o.entrantId} aria-label={r ? `${entrantLabel(s, e.entrantId)} versus ${entrantLabel(s, o.entrantId)}: ${summary(r)}` : 'Same entrant'}>{r ? <>{wdl(r)}<small>{r.played ? percent(r.scoreRate) : '—'}</small></> : '—'}</td>; })}</tr>)}</tbody></table></div>
    <div className="pairwise-mobile"><label htmlFor="pairwise-entrant">Entrant to compare</label><select id="pairwise-entrant" value={selected} onChange={e => setSelected(e.target.value)}>{s.entrants.map(e => <option value={e.entrantId} key={e.entrantId}>{entrantLabel(s, e.entrantId)}</option>)}</select><ul>{s.entrants.filter(e => e.entrantId !== selected).map(e => <li key={e.entrantId}><strong>{entrantLabel(s, e.entrantId)}</strong><span>{summary(matrix[selected][e.entrantId])}</span></li>)}</ul></div>
  </section>;
}
