name: Build & Publish

on:
  push:
    branches: [ main ]

env:
  IMAGE_API:  andrewcukierwar/board-game-ai-api
  IMAGE_UI:   andrewcukierwar/board-game-ai-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/api.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:${{ github.sha }}
            ${{ env.IMAGE_API }}:latest

      - name: Build & push UI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/ui.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_UI }}:${{ github.sha }}
            ${{ env.IMAGE_UI }}:latest

      # ---------- Trigger Render ---------- 
      - name: Deploy to Render
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST "$DEPLOY_HOOK"
