name: Docker-lite CI/CD
on:
  push:
    branches: [main]   # rebuild on every merge
  workflow_dispatch:   # manual “Run workflow” button

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # -- checkout code ------------------------------------------------------
      - uses: actions/checkout@v4

      # -- set up Buildx (needed for multi-arch or cache) ---------------------
      - uses: docker/setup-buildx-action@v3

      # -- log in to ghcr.io --------------------------------------------------
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -- generate tags & labels --------------------------------------------
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch        # e.g. main → :main
            type=sha                     # :sha-abcdef
            type=raw,value=latest

      # -- build and push the image ------------------------------------------
      - uses: docker/build-push-action@v5   # official Buildx action :contentReference[oaicite:1]{index=1}
        with:
          context: .
          file: docker/api.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to:   type=inline

      # # -- ping Render so it pulls the new image -----------------------------
      # - name: Trigger Render Deploy
      #   env:
      #     HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl -fsSL -X POST "$HOOK"
